package model;
// Generated 8/03/2016 11:28:58 PM by Hibernate Tools 4.3.1



/**
 * Ingreso generated by hbm2java
 */
public class Ingreso  implements java.io.Serializable {


     private int idIngreso;
     private String nickname;
     private Integer contrasenia;

    public Ingreso() {
    }

	
    public Ingreso(int idIngreso) {
        this.idIngreso = idIngreso;
    }
    public Ingreso(int idIngreso, String nickname, Integer contrasenia) {
       this.idIngreso = idIngreso;
       this.nickname = nickname;
       this.contrasenia = contrasenia;
    }
   
    public int getIdIngreso() {
        return this.idIngreso;
    }
    
    public void setIdIngreso(int idIngreso) {
        this.idIngreso = idIngreso;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public Integer getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(Integer contrasenia) {
        this.contrasenia = contrasenia;
    }




}


